# Generated by Django 2.1.7 on 2019-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_auto_20190416_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
