# Generated by Django 2.1.7 on 2019-04-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_auto_20190416_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
